### PR TITLE
Styles and Selected Item functionality

### PR DESCRIPTION
**Pull request by babak49**
Added basic styles for input, suggestion wrapper, group and item.
Added functionality to highlight selected item

### CODE REVIEW

**Comment by QuietOmen** [comment]
@babak49 This good to me. :+1: Also I was going to move away from radium in my next update to this project, but I can't find a good solution that will allow me to integrate css with the components without the user having to attach it somewhere.

**Comment by babak49** [comment]
@QuietOmen What do you think about SCSS with variables? We can add some styles here and they can be easily overridden by user.

**Comment by QuietOmen** [comment]
Yeah I like scss but I want the default styles to be included automatically with the components...it's an extremely small thing but I was trying to avoid having the library's user code a 

```<link rel="stylesheet" type="text/css" href="default_theme.css">``` 

Maybe I should just get over that and simply have them write that out. Does that make sense?

**Comment by babak49** [comment]
@QuietOmen I don't think that is a good idea. In my opinion, we should create .scss file with some specific namespace and wrap our component in it. We will import our styles to component and they will be included into a component. Also, in that case user will be able to inherit or rewrite styles in that way that he want.
It could be implemented in a similar way that we are doing in Local. 
Does that make sense?

**Comment by QuietOmen** [comment]
Yeah it does...I just remember trying something like that last time and I couldn't get the bundled files to include the css correctly with all of the various loaders that webpack/scss used. I'll take a swing at it and have you help me out if I can't figure it out.

**Comment by QuietOmen** [comment]
Oh and I found an error, I think it's from you changing a couple of the setState areas but I can't filter based on my typing. I'll look things over and figure out what happened.

**Pull request merged**
